### ISSUE TITLE
Fatal: repository 'https://github.com/jdevelop/fs4map/' not found

### ISSUE THREAD

**Issue by tlaak** [jdevelop/foursquare-kml#1]
I've been looking for a tool to convert my Foursquare checkins to KML as their feed links are not working anymore. I had high hopes of using yours, but this dependency is not found so I can't install it. Would you by any chance have a moment of your time to check if this library could be fixed?

**Comment by jdevelop** [comment]
Should work fine now, with go modules.

**Comment by tlaak** [comment]
Nope, still broken as https://github.com/jdevelop/fs4map/ is not available anymore. 

```
> go build
can't load package: package github.com/jdevelop/fs4map: unknown import path "github.com/jdevelop/fs4map": cannot find module providing package github.com/jdevelop/fs4map
```

**Comment by jdevelop** [comment]
try now, I renamed the repository so it should work fine in `$GOPATH` too

**Comment by tlaak** [comment]
I still get the same complaint when I run `go build`, which is weird. `go get` completes without nags though.
